apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: handdoff-service
  namespace: csp-development
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: handdoff-service
  targetCPUUtilizationPercentage: 40
---
apiVersion: v1
kind: Service
metadata:
  name: handdoff-service
  namespace: csp-development
spec:
  selector:
    app: handdoff-service
  type: NodePort
  ports:
  - name: handdoff-service
    protocol: HTTP
    port: 9001
    nodePort: 32008
---
apiVersion: apps/v1
kind: Deployment
metadata:

  name: handdoff-service
  namespace: csp-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handdoff-service
  template:
    metadata:
      labels:
        app: handdoff-service
    spec:
      containers:
      - name: handdoff-service
        image: [imagename-latest]
        imagePullPolicy: IfNotPresent
               
        resources:
          limits:
            memory: "200Mi"
            cpu: "0.020"
          requests:
            memory: "200Mi"
            cpu: "0.020"
        #command: [ "/bin/sh", "-c", "ls /Orchestration" ]
        ports:
        - name: handdoff-service
          containerPort: 7000